/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;

public class App {


    public static void main(String[] args) throws IOException {

        ArrayList<String> jsonStrings = getQuotesData();
        ArrayList<Quote> myQuotes = quotify(jsonStrings);


        for(Quote quote: myQuotes){
            System.out.println(quote);
        }


    }

    public static ArrayList<Quote> quotify(ArrayList<String> quoteJSONString){
        ArrayList<Quote>  quotes = new ArrayList<>();

        for(String string: quoteJSONString){
            System.out.println(string);
            Gson gson = new GsonBuilder().serializeNulls().create();
            Quote quoteFromJsonString = gson.fromJson(string, Quote.class );
            quotes.add(quoteFromJsonString);
        }

        return quotes;
    }


    public static ArrayList<String> getQuotesData() throws IOException {

        Path path = FileSystems.getDefault().getPath("assets", "recentquotes.json");
        System.out.println(path);

        BufferedReader reader = Files.newBufferedReader(path, StandardCharsets.UTF_8);
        String output = "";
        StringBuilder stringBuilder = new StringBuilder();

        while((output = reader.readLine()) != null){
            stringBuilder.append(output);
//            System.out.println(output);
        }

        String[] objectArray = stringBuilder.toString().split("},",-1);
        ArrayList<String> outputArray = new ArrayList<>();

        for(String string: objectArray){
            if(string.startsWith("[")){
                string = string.substring(1);
            }
            if(string.endsWith("]")){
                string = string.substring(1,string.length()-1);
                System.out.println(string);
                outputArray.add(string);
                continue;
            }

            outputArray.add(string+"}");
        }

        return outputArray;
    }
}
